---
- name: Install Java on Amazon Linux
  hosts: all
  become: yes
  tasks:
    - name: Ensure the system is updated
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Java 
      yum:
        name: java-21-amazon-corretto
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Display Java version
      debug:
        msg: "{{ java_version.stdout_lines }}"

