---
- name: Install Jenkins on Amazon Linux
  hosts: Jenkins
  become: yes
  tasks:
    # Step 1: Update the system
    - name: Ensure the system is updated
      yum:
        name: "*"
        state: latest
        update_cache: yes

    # Step 3: Add the Jenkins repository
    - name: Add Jenkins repository
      copy:
        content: |
          [jenkins]
          name=Jenkins
          baseurl=http://pkg.jenkins.io/redhat-stable/
          gpgcheck=0
          gpgkey=https://pkg.jenkins.io/redhat/jenkins.io.key
          enabled=1
        dest: /etc/yum.repos.d/jenkins.repo

    # Step 4: Import the Jenkins GPG key
    - name: Import Jenkins GPG key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key

    # Step 5: Install Jenkins
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

   # Step 6: Start and enable the Jenkins service
    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
